### ISSUE TITLE
No way to re-open the properties panel if closed

### ISSUE THREAD

**Issue by udw82145** [bbepis/KKManager#2]
Short of deleting the config file in the user Appdata/roaming folder, there is apparently no way to restore the properties panel once closed (via x button).

I tried playing with the menu options for a few minutes, but I think this is indeed the case. 
Probably no-one ever reported this cos there would be no conceivable reason to close it.

**Comment by ManlyMarco** [comment]
I actually already fixed it in 2ed16168c89354fb440f7dbb75ba87db2b0def56, just didn't make a release yet. Either way, thanks for the report!
