### ISSUE TITLE
Question regarding a few of the traits attached to the cards.

### ISSUE THREAD

**Issue by Giira0** [bbepis/KKManager#4]
Hi, I'm using your utility for the first time, and noticed there are values for aggression, kindness, and  diligence. However they are all displayed as "0" rather than the values that are typically listed in the koikatu wiki and elsewhere as being the ones linked to their personalities. 

I wanted to make sure if then those values were modifiers or if the utility simply doesn't alter them (since none of them are listed as anything aside zeros)?  Also if I did so, how would I change those values? Changes aren't retained switching between cards.

I haven't been able to find the new values for the personalities added with the DLC listed anywhere as of yet, so I didn't want to mess with these before making sure how the functionality of your utility altered those values. Thanks for your help and work put in on this utility. 

EDIT: I have been made aware that the reason I haven't been able to make changes to character cards is because.... you can't... "yet" So basically I'll be looking forward to seeing what you come up with and keep learning more about the various mods/utilities you all have put a lot of time in effort into making. Thank you. :D

**Comment by ManlyMarco** [comment]
Yeah, modifying card data is not yet implemented. Each of these parameters goes on a 0-100 scale and don't directly affect the relationship or anger which are separate parameters, you can play around with them with https://github.com/ManlyMarco/KoikatuCheatTools.
